name: Website

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  checks:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Test Build
        run: |
          yarn install --frozen-lockfile;
          cd website;
          yarn install --frozen-lockfile;
          yarn build;
  gh-release:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.GH_PAGES_DEPLOY }}
      - name: Release to GitHub Pages
        env:
          USE_SSH: true
          GIT_USER: git
        run: |
          set -e;
          git config --global user.email "mail@aniddan.com";
          git config --global user.name "Iddan Aaronsohn";
          yarn install --frozen-lockfile;
          yarn build-storybook;
          mkdir -p website/static/storybook;
          cp -r storybook-static/* website/static/storybook;
          cd website;
          yarn install --frozen-lockfile;
          yarn deploy;
